#############################################################################
# Makefile for building: targettracking2
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Apr 26 10:54:49 2012
# Project:  targettracking2.pro
# Template: app
# Command: /home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/qmake -o Makefile targettracking2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/default -I. -I../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/include/QtCore -I../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/include/QtGui -I../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		ttmap.cpp \
		settingdialog.cpp moc_mainwindow.cpp \
		moc_ttmap.cpp \
		moc_settingdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		ttmap.o \
		settingdialog.o \
		moc_mainwindow.o \
		moc_ttmap.o \
		moc_settingdialog.o
DIST          = ../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		targettracking2.pro
QMAKE_TARGET  = targettracking2
DESTDIR       = 
TARGET        = targettracking2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_settingdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: targettracking2.pro  ../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/default/qmake.conf ../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile targettracking2.pro
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../../../programs/qtsdk/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile targettracking2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/targettracking21.0.0 || $(MKDIR) .tmp/targettracking21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/targettracking21.0.0/ && $(COPY_FILE) --parents mainwindow.h ttmap.h settingdialog.h .tmp/targettracking21.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp ttmap.cpp settingdialog.cpp .tmp/targettracking21.0.0/ && $(COPY_FILE) --parents mainwindow.ui settingdialog.ui .tmp/targettracking21.0.0/ && (cd `dirname .tmp/targettracking21.0.0` && $(TAR) targettracking21.0.0.tar targettracking21.0.0 && $(COMPRESS) targettracking21.0.0.tar) && $(MOVE) `dirname .tmp/targettracking21.0.0`/targettracking21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/targettracking21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_ttmap.cpp moc_settingdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_ttmap.cpp moc_settingdialog.cpp
moc_mainwindow.cpp: settingdialog.h \
		mainwindow.h
	/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_ttmap.cpp: ttmap.h
	/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) ttmap.h -o moc_ttmap.cpp

moc_settingdialog.cpp: settingdialog.h
	/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) settingdialog.h -o moc_settingdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settingdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settingdialog.h
ui_mainwindow.h: mainwindow.ui
	/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_settingdialog.h: settingdialog.ui
	/home/hcy/programs/qtsdk/Desktop/Qt/4.8.0/gcc/bin/uic settingdialog.ui -o ui_settingdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		settingdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		settingdialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ttmap.o: ttmap.cpp ttmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ttmap.o ttmap.cpp

settingdialog.o: settingdialog.cpp settingdialog.h \
		ui_settingdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingdialog.o settingdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ttmap.o: moc_ttmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ttmap.o moc_ttmap.cpp

moc_settingdialog.o: moc_settingdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingdialog.o moc_settingdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

